name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  UBUNTU_RELESE: "noble"
jobs:
  build-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          tags: localhost:5000/manypython-deps:${{ env.UBUNTU_RELESE }}
          outputs: type=docker,dest=manypython-deps.tar
          file: Dockerfile.deps

      - uses: actions/upload-artifact@v4
        with:
          name: manypython-deps
          path: manypython-deps.tar

  build-binary:
    needs: build-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
      fail-fast: false
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: manypython-deps

      - name: Load image
        run: |
          docker load --input manypython-deps.tar
          docker push localhost:5000/manypython-deps:$UBUNTU_RELESE
        env:
          UBUNTU_RELESE: ${{ env.UBUNTU_RELESE }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          tags: localhost:5000/manypython-bin:${{ matrix.python-version }}-${{ env.UBUNTU_RELESE }}
          outputs: type=docker,dest=manypython-bin-${{ matrix.python-version }}.tar
          file: Dockerfile.build
          build-args: |
            MANYPYTHON_DEPS_IMAGE=localhost:5000/manypython-deps

      - uses: actions/upload-artifact@v4
        with:
          name: manypython-bin-${{ matrix.python-version }}
          path: manypython-bin-${{ matrix.python-version }}.tar

  build-base:
    needs: build-binary
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: manypython-bin-*
          merge-multiple: true

      - name: Load image
        run: |
          docker load --input manypython-bin-3.9.tar
          docker load --input manypython-bin-3.10.tar
          docker load --input manypython-bin-3.11.tar
          docker load --input manypython-bin-3.12.tar
          docker load --input manypython-bin-3.13.tar
          docker push localhost:5000/manypython-bin:3.9-$UBUNTU_RELESE
          docker push localhost:5000/manypython-bin:3.10-$UBUNTU_RELESE
          docker push localhost:5000/manypython-bin:3.11-$UBUNTU_RELESE
          docker push localhost:5000/manypython-bin:3.12-$UBUNTU_RELESE
          docker push localhost:5000/manypython-bin:3.13-$UBUNTU_RELESE
        env:
          UBUNTU_RELESE: ${{ env.UBUNTU_RELESE }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          tags: localhost:5000/manypython-base:${{ env.UBUNTU_RELESE }}
          outputs: type=docker,dest=manypython-base.tar
          file: Dockerfile.base
          build-args: |
            MANYPYTHON_BIN_IMAGE=localhost:5000/manypython-bin

      - uses: actions/upload-artifact@v4
        with:
          name: manypython-base
          path: manypython-base.tar

  build-dev:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: manypython-base

      - name: Load image
        run: docker load --input manypython-base.tar

      - uses: actions/checkout@v4

      - run: npm install -g @devcontainers/cli

      - run: devcontainer build --image-name manypython-dev --workspace-folder .

      - run: docker save -o manypython-dev.tar manypython-dev

      - uses: actions/upload-artifact@v4
        with:
          name: manypython-dev
          path: manypython-dev.tar
